/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as ServicesSlugRouteImport } from './routes/services_.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as Play_GroundIpLocatorRouteImport } from './routes/Play_Ground.Ip-Locator'
import { Route as Play_GroundIpGraberRouteImport } from './routes/Play_Ground.Ip-Graber'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services_/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const Play_GroundIpLocatorRoute = Play_GroundIpLocatorRouteImport.update({
  id: '/Play_Ground/Ip-Locator',
  path: '/Play_Ground/Ip-Locator',
  getParentRoute: () => rootRouteImport,
} as any)
const Play_GroundIpGraberRoute = Play_GroundIpGraberRouteImport.update({
  id: '/Play_Ground/Ip-Graber',
  path: '/Play_Ground/Ip-Graber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faq': typeof FaqRoute
  '/services': typeof ServicesRouteWithChildren
  '/team': typeof TeamRoute
  '/Play_Ground/Ip-Graber': typeof Play_GroundIpGraberRoute
  '/Play_Ground/Ip-Locator': typeof Play_GroundIpLocatorRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/faq': typeof FaqRoute
  '/team': typeof TeamRoute
  '/Play_Ground/Ip-Graber': typeof Play_GroundIpGraberRoute
  '/Play_Ground/Ip-Locator': typeof Play_GroundIpLocatorRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faq': typeof FaqRoute
  '/services': typeof ServicesRouteWithChildren
  '/team': typeof TeamRoute
  '/Play_Ground/Ip-Graber': typeof Play_GroundIpGraberRoute
  '/Play_Ground/Ip-Locator': typeof Play_GroundIpLocatorRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/services_/$slug': typeof ServicesSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/courses'
    | '/faq'
    | '/services'
    | '/team'
    | '/Play_Ground/Ip-Graber'
    | '/Play_Ground/Ip-Locator'
    | '/courses/$slug'
    | '/services/$slug'
    | '/courses/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/faq'
    | '/team'
    | '/Play_Ground/Ip-Graber'
    | '/Play_Ground/Ip-Locator'
    | '/courses/$slug'
    | '/services/$slug'
    | '/courses'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact-us'
    | '/courses'
    | '/faq'
    | '/services'
    | '/team'
    | '/Play_Ground/Ip-Graber'
    | '/Play_Ground/Ip-Locator'
    | '/courses/$slug'
    | '/services_/$slug'
    | '/courses/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  FaqRoute: typeof FaqRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TeamRoute: typeof TeamRoute
  Play_GroundIpGraberRoute: typeof Play_GroundIpGraberRoute
  Play_GroundIpLocatorRoute: typeof Play_GroundIpLocatorRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/services_/$slug': {
      id: '/services_/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/Play_Ground/Ip-Locator': {
      id: '/Play_Ground/Ip-Locator'
      path: '/Play_Ground/Ip-Locator'
      fullPath: '/Play_Ground/Ip-Locator'
      preLoaderRoute: typeof Play_GroundIpLocatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Play_Ground/Ip-Graber': {
      id: '/Play_Ground/Ip-Graber'
      path: '/Play_Ground/Ip-Graber'
      fullPath: '/Play_Ground/Ip-Graber'
      preLoaderRoute: typeof Play_GroundIpGraberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface ServicesRouteChildren {
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  CoursesRoute: CoursesRouteWithChildren,
  FaqRoute: FaqRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TeamRoute: TeamRoute,
  Play_GroundIpGraberRoute: Play_GroundIpGraberRoute,
  Play_GroundIpLocatorRoute: Play_GroundIpLocatorRoute,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
